language: node_js
node_js:
    - "0.10"
sudo: required
python: 
    - "2.7"
addons:
    postgresql: "9.3"
install:
    - npm install -g gulp
    - sudo pip install -r AviPost/requirements.txt
before_script:
    - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
    - psql -d travis_ci_test -c 'CREATE EXTENSION postgis' -U postgres
    - cd AviPost/avipost
    - python manage.py migrate --settings=avipost.settings.travis_ci
    - python manage.py runserver --settings=avipost.settings.travis_ci &
script: gulp e2e
